/*******************************************************************************
 * Copyright (c) 2000, 2014 IBM Corporation and others.
 *
 * This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License 2.0
 * which accompanies this distribution, and is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *  
 * Contributors:
 *     IBM Corporation - initial API and implementation
 *******************************************************************************/
package org.eclipse.jdt.internal.compiler.parser;

/*An interface that contains static declarations for some basic information
 about the parser such as the number of rules in the grammar, the starting state, etc...*/
public interface ParserBasicInformation {

	public final static int
      // BEGIN_AUTOGENERATED_REGION

					ERROR_SYMBOL = 130,
					MAX_NAME_LENGTH = 41,
					NUM_STATES = 1161,

					NT_OFFSET = 130,
					SCOPE_UBOUND = 293,
					SCOPE_SIZE = 294,
					LA_STATE_OFFSET = 16448,
					MAX_LA = 1,
					NUM_RULES = 862,
					NUM_TERMINALS = 130,
					NUM_NON_TERMINALS = 395,
					NUM_SYMBOLS = 525,
					START_STATE = 954,
					EOFT_SYMBOL = 60,
					EOLT_SYMBOL = 60,
					ACCEPT_ACTION = 16447,
					ERROR_ACTION = 16448;
}
