/*******************************************************************************
 * Copyright (c) 2000, 2019 IBM Corporation and others.
 *
 * This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License 2.0
 * which accompanies this distribution, and is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *     IBM Corporation - initial API and implementation
 *******************************************************************************/
package org.eclipse.jdt.internal.compiler.parser;

/**
 * IMPORTANT NOTE: These constants are dedicated to the internal Scanner implementation.
 * It is mirrored in org.eclipse.jdt.core.compiler public package where it is API.
 * The mirror implementation is using the backward compatible ITerminalSymbols constant
 * definitions (stable with 2.0), whereas the internal implementation uses TerminalTokens
 * which constant values reflect the latest parser generation state.
 */
/**
 * Maps each terminal symbol in the java-grammar into a unique integer.
 * This integer is used to represent the terminal when computing a parsing action.
 *
 * Disclaimer : These constant values are generated automatically using a Java
 * grammar, therefore their actual values are subject to change if new keywords
 * were added to the language (for instance, 'assert' is a keyword in 1.4).
 */
public interface TerminalTokens {

	// special tokens not part of grammar - not autogenerated
	int TokenNameNotAToken = 0,
							TokenNameWHITESPACE = 1000,
							TokenNameCOMMENT_LINE = 1001,
							TokenNameCOMMENT_BLOCK = 1002,
							TokenNameCOMMENT_JAVADOC = 1003;

	// BEGIN_AUTOGENERATED_REGION
	int TokenNameIdentifier = 22,
							TokenNameabstract = 52,
							TokenNameassert = 80,
							TokenNameboolean = 103,
							TokenNamebreak = 81,
							TokenNamebyte = 104,
							TokenNamecase = 105,
							TokenNamecatch = 106,
							TokenNamechar = 107,
							TokenNameclass = 69,
							TokenNamecontinue = 82,
							TokenNameconst = 131,
							TokenNamedefault = 76,
							TokenNamedo = 83,
							TokenNamedouble = 108,
							TokenNameelse = 116,
							TokenNameenum = 74,
							TokenNameextends = 90,
							TokenNamefalse = 38,
							TokenNamefinal = 53,
							TokenNamefinally = 115,
							TokenNamefloat = 109,
							TokenNamefor = 84,
							TokenNamegoto = 132,
							TokenNameif = 85,
							TokenNameimplements = 127,
							TokenNameimport = 110,
							TokenNameinstanceof = 17,
							TokenNameint = 111,
							TokenNameinterface = 73,
							TokenNamelong = 112,
							TokenNamenative = 54,
							TokenNamenew = 36,
							TokenNamenull = 39,
							TokenNamepackage = 89,
							TokenNameprivate = 55,
							TokenNameprotected = 56,
							TokenNamepublic = 57,
							TokenNamereturn = 86,
							TokenNameshort = 113,
							TokenNamestatic = 40,
							TokenNamestrictfp = 58,
							TokenNamesuper = 34,
							TokenNameswitch = 59,
							TokenNamesynchronized = 51,
							TokenNamethis = 35,
							TokenNamethrow = 77,
							TokenNamethrows = 124,
							TokenNametransient = 60,
							TokenNametrue = 41,
							TokenNametry = 87,
							TokenNamevoid = 114,
							TokenNamevolatile = 61,
							TokenNamewhile = 78,
							TokenNamemodule = 117,
							TokenNameopen = 118,
							TokenNamerequires = 119,
							TokenNametransitive = 125,
							TokenNameexports = 120,
							TokenNameopens = 121,
							TokenNameto = 128,
							TokenNameuses = 122,
							TokenNameprovides = 123,
							TokenNamewith = 129,
							TokenNameIntegerLiteral = 42,
							TokenNameLongLiteral = 43,
							TokenNameFloatingPointLiteral = 44,
							TokenNameDoubleLiteral = 45,
							TokenNameCharacterLiteral = 46,
							TokenNameStringLiteral = 47,
							TokenNameTextBlock = 48,
							TokenNamePLUS_PLUS = 2,
							TokenNameMINUS_MINUS = 3,
							TokenNameEQUAL_EQUAL = 19,
							TokenNameLESS_EQUAL = 12,
							TokenNameGREATER_EQUAL = 13,
							TokenNameNOT_EQUAL = 20,
							TokenNameLEFT_SHIFT = 18,
							TokenNameRIGHT_SHIFT = 14,
							TokenNameUNSIGNED_RIGHT_SHIFT = 16,
							TokenNamePLUS_EQUAL = 91,
							TokenNameMINUS_EQUAL = 92,
							TokenNameMULTIPLY_EQUAL = 93,
							TokenNameDIVIDE_EQUAL = 94,
							TokenNameAND_EQUAL = 95,
							TokenNameOR_EQUAL = 96,
							TokenNameXOR_EQUAL = 97,
							TokenNameREMAINDER_EQUAL = 98,
							TokenNameLEFT_SHIFT_EQUAL = 99,
							TokenNameRIGHT_SHIFT_EQUAL = 100,
							TokenNameUNSIGNED_RIGHT_SHIFT_EQUAL = 101,
							TokenNameOR_OR = 31,
							TokenNameAND_AND = 30,
							TokenNamePLUS = 4,
							TokenNameMINUS = 5,
							TokenNameNOT = 65,
							TokenNameREMAINDER = 9,
							TokenNameXOR = 24,
							TokenNameAND = 21,
							TokenNameMULTIPLY = 8,
							TokenNameOR = 27,
							TokenNameTWIDDLE = 66,
							TokenNameDIVIDE = 10,
							TokenNameGREATER = 15,
							TokenNameLESS = 11,
							TokenNameLPAREN = 23,
							TokenNameRPAREN = 26,
							TokenNameLBRACE = 49,
							TokenNameRBRACE = 33,
							TokenNameLBRACKET = 6,
							TokenNameRBRACKET = 68,
							TokenNameSEMICOLON = 25,
							TokenNameQUESTION = 29,
							TokenNameCOLON = 64,
							TokenNameCOMMA = 32,
							TokenNameDOT = 1,
							TokenNameEQUAL = 75,
							TokenNameAT = 37,
							TokenNameELLIPSIS = 126,
							TokenNameARROW = 102,
							TokenNameCOLON_COLON = 7,
							TokenNameBeginLambda = 50,
							TokenNameBeginIntersectionCast = 67,
							TokenNameBeginTypeArguments = 88,
							TokenNameElidedSemicolonAndRightBrace = 70,
							TokenNameAT308 = 28,
							TokenNameAT308DOTDOTDOT = 130,
							TokenNameBeginCaseExpr = 71,
							TokenNameRestrictedIdentifierYield = 79,
							TokenNameSPEC_CLAUSE_START = 62,
							TokenNameSPEC_CLAUSE_END = 72,
							TokenNameEOF = 63,
							TokenNameERROR = 133;
}
